
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND COMMA CP ENTITY EQUAL FIND FROM INFO LIMIT NAME NUMBER POSTAL SELECT SEMICOLON TYPE WHEREstart : statement statement :  FIND  ENTITIES WHERE CONDITION SEMICOLON\n    | FIND  ENTITIES WHERE CONDITION  LIMIT NUMBER SEMICOLON\n    | SELECT ENTITIES FROM ENTITY EQUAL INFO CONDITION  : CP EQUAL POSTAL AND  WORK WORK :  TYPE EQUAL NAME ENTITIES : ENTITY\n    | ENTITIES COMMA ENTITY '
    
_lr_action_items = {'FIND':([0,],[3,]),'SELECT':([0,],[4,]),'$end':([1,2,15,21,22,],[0,-1,-2,-4,-3,]),'ENTITY':([3,4,9,10,],[6,6,13,14,]),'WHERE':([5,6,13,],[8,-7,-8,]),'COMMA':([5,6,7,13,],[9,-7,9,-8,]),'FROM':([6,7,13,],[-7,10,-8,]),'CP':([8,],[12,]),'SEMICOLON':([11,19,24,27,],[15,22,-5,-6,]),'LIMIT':([11,24,27,],[16,-5,-6,]),'EQUAL':([12,14,25,],[17,18,26,]),'NUMBER':([16,],[19,]),'POSTAL':([17,],[20,]),'INFO':([18,],[21,]),'AND':([20,],[23,]),'TYPE':([23,],[25,]),'NAME':([26,],[27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'statement':([0,],[2,]),'ENTITIES':([3,4,],[5,7,]),'CONDITION':([8,],[11,]),'WORK':([23,],[24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> statement','start',1,'p_start','langage.py',76),
  ('statement -> FIND ENTITIES WHERE CONDITION SEMICOLON','statement',5,'p_satement_expr','langage.py',82),
  ('statement -> FIND ENTITIES WHERE CONDITION LIMIT NUMBER SEMICOLON','statement',7,'p_satement_expr','langage.py',83),
  ('statement -> SELECT ENTITIES FROM ENTITY EQUAL INFO','statement',6,'p_satement_expr','langage.py',84),
  ('CONDITION -> CP EQUAL POSTAL AND WORK','CONDITION',5,'p_expression_condition','langage.py',94),
  ('WORK -> TYPE EQUAL NAME','WORK',3,'p_expression_work','langage.py',102),
  ('ENTITIES -> ENTITY','ENTITIES',1,'p_expression_expr','langage.py',109),
  ('ENTITIES -> ENTITIES COMMA ENTITY','ENTITIES',3,'p_expression_expr','langage.py',110),
]
