name: PA_TDL_Test

on: [push]

jobs:
  docker:
      #needs: [build]
      runs-on: ubuntu-22.04
      
      steps:
        - name: Checkout
          uses: actions/checkout@v3.1.0
          
        - name: Login to Docker Hub
          uses: docker/login-action@v2.1.0
          with:
            username: ari1008
            password: dckr_pat_n-DRFcAA4X6aT8_slrCeD9jzBFg
            logout: true

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@v4.1.1
          with:
            images: ari1008/web-aristide
        
        
        - name: Build and push Docker image
          uses: docker/build-push-action@v3
          with:
            context:  ./prod_dockerfile/web/Dockerfile
            push: true
            tags: ari1008/web-aristide
            
