name: PA_TDL_Test

on: [push]

jobs:
  docker:
      #needs: [build]
      runs-on: ubuntu-22.04
      
      steps:
        - name: Checkout
          uses: actions/checkout@v3.1.0
          
        - name: Afficher les détails du fichier PA_TDL_Test
          run: ls -al PA_TDL_Test
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2.1.0
          with:
            username: ari1008
            password: dckr_pat_n-DRFcAA4X6aT
